### ISSUE TITLE
Add bulk fields for batch start and end

### ISSUE THREAD

**Issue by derekssmith** [naveego/dataflow-contracts#64]
Add bulk fields for batch start and end

## Story
As a Naveego Platform user
I would like to bulk load my transactional replication data
So that I can achieve better replication performance for transactional data replications

## Acceptance Criteria

GIVEN a transactional GR
WHEN a connection is being created or selected for a replication job
THEN only plugins flagged for bulk replication capability are available to the user
AND the bulk option is automatically enabled for that plugin

GIVEN an active bulk replication job
WHEN data is queued up for replication
THEN it is replicated using 'bulk' options for better performance

## Additional Context
Existing plugins that need this option added
Oracle Autonomous Data Warehouse
Future Plugins that will need this option:
Snowflake
Redshift
Azure SQL Data WH

# Ideas from grooming / backlog checkup
Ingest -> Kafka Topic -> job that reads kafka topic switching from regular mode to bulk load
Need ability to load plugins from private repositories or manually publish them

- [ ] requires naveegoinc/go-between#307
- [x] requires naveegoinc/nucleus#7
- [ ] requires naveegoinc/nucleus#9
- [x] requires naveegoinc/nucleus#10
- [x] requires naveegoinc/nucleus#13
- [ ] requires naveegoinc/go-between#314

 required by naveegoinc/stories#1696
